from __future__ import annotations

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
AUDIT_DOC = (
    REPO_ROOT
    / "docs"
    / "dp_native_training_sufficiency_development_base_plus_addon_static_dp_reward_fixed_artifact_fallback_risk_training_data_validator_extension_fixed_artifact_acceptance_audit.md"
)
ITERATION_AUDIT = REPO_ROOT / "docs" / "diffusion_planner_v8_iteration_audit.md"


def _audit() -> str:
    return AUDIT_DOC.read_text(encoding="utf-8")


def test_validator_acceptance_records_fixed_nonformal_dataset_identity() -> None:
    text = _audit()

    for needle in [
        "source_artifact_scope=broader_nonformal_fixed_evaluation_artifact",
        "formal_seeds_11_12_13_used=False",
        "source_dataset_json=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_builder_acceptance_f632c44_20260624T133402Z/dataset.json",
        "source_dataset_sha256=1a7593ad2ef4eb138187e56635c597e4537f4533e7033936acf6801a1108e9bf",
        "validator_output_dir=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_validator_acceptance_f4ea755_20260624T142300Z",
        "validator_output_json_sha256=572888123f53ebe6921a5e9a6fb920c2e425e5a1e578a259d0ce03f76a85a44b",
        "validator_output_md_sha256=e57c15b6772e0202fe76fec20d220e435c1010aab7bc410fb45230277fc9ab6a",
        "autodl_DP_HEAD_at_acceptance=7a1d33da277a1992ec474b5383a0c963c72e04e4",
        "current_source_artifact_scope=broader_nonformal_fixed_evaluation_artifact",
        "current_source_dataset_json=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_builder_acceptance_52f8d20_20260624T195018Z/dataset.json",
        "current_source_dataset_sha256=0978687b1f7582f6644eb9598bdc5a9e03494ad227d1627bd603d54e15efb8e2",
        "current_unique_source_logs=7",
        "current_strict_formal_seed_path_matches=0",
        "current_formal_seeds_11_12_13_used=False",
        "current_validator_output_dir=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_validator_acceptance_0ed8c92_20260624T201719Z",
        "current_validator_output_json_sha256=276ed840e674733861123bde0c1fa45474fbcba6d23d7faa83e53abbacd7b078",
        "current_validator_output_md_sha256=e57c15b6772e0202fe76fec20d220e435c1010aab7bc410fb45230277fc9ab6a",
        "autodl_DP_HEAD_at_revalidation=7a1d33da277a1992ec474b5383a0c963c72e04e4",
        "latest_source_artifact_scope=broader_nonformal_fixed_evaluation_artifact",
        "latest_source_dataset_json=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_builder_acceptance_6adb800_20260625T020016Z/dataset.json",
        "latest_source_dataset_sha256=9dae6215f7b35cd142c37da80c92b38cac1263ee229a5ecb9c4e7c7cd4785018",
        "latest_unique_source_logs=7",
        "latest_strict_formal_seed_path_matches=0",
        "latest_formal_seeds_11_12_13_used=False",
        "latest_validator_output_dir=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_validator_acceptance_4aeb061_20260625T022753Z",
        "latest_validator_output_json_sha256=039b3e41f866434e187a9f679cbc964d6fe35d5406896e53ec38d8f70db40c52",
        "latest_validator_output_md_sha256=e57c15b6772e0202fe76fec20d220e435c1010aab7bc410fb45230277fc9ab6a",
        "camp_head_at_latest_revalidation=4aeb061e38d037fa3fb2bced1c34e283bac1307d",
        "autodl_DP_HEAD_at_latest_revalidation=7a1d33da277a1992ec474b5383a0c963c72e04e4",
        "current_head_source_dataset_json=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_builder_acceptance_6adb800_20260625T020016Z/dataset.json",
        "current_head_source_dataset_sha256=9dae6215f7b35cd142c37da80c92b38cac1263ee229a5ecb9c4e7c7cd4785018",
        "current_head_source_artifact_scope=broader_nonformal_fixed_evaluation_artifact",
        "current_head_unique_source_logs=7",
        "current_head_strict_formal_seed_path_matches=0",
        "current_head_formal_seeds_11_12_13_used=False",
        "current_head_validator_output_dir=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_validator_acceptance_b572505_20260625T091546Z",
        "current_head_validator_output_json_sha256=039b3e41f866434e187a9f679cbc964d6fe35d5406896e53ec38d8f70db40c52",
        "current_head_validator_output_md_sha256=e57c15b6772e0202fe76fec20d220e435c1010aab7bc410fb45230277fc9ab6a",
        "camp_head_at_current_head_revalidation=b5725054734ad64d159fe0c993bda2d85a52c81b",
        "autodl_DP_HEAD_at_current_head_revalidation=7a1d33da277a1992ec474b5383a0c963c72e04e4",
        "head_0c7eada_source_dataset_json=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_builder_acceptance_e35f1e4_20260625T132102Z/dataset.json",
        "head_0c7eada_source_dataset_sha256=79e8ddd27b06f6d377819c64dace333e0e36af088505fe784bfee24f89f956c0",
        "head_0c7eada_source_artifact_scope=broader_nonformal_fixed_evaluation_artifact",
        "head_0c7eada_unique_source_logs=7",
        "head_0c7eada_strict_formal_seed_path_matches=0",
        "head_0c7eada_formal_seeds_11_12_13_used=False",
        "head_0c7eada_validator_output_dir=/root/autodl-tmp/camp_dp_native_fallback_risk_training_data_validator_acceptance_0c7eada_20260625T141534Z",
        "head_0c7eada_validator_output_json_sha256=4baaf581141c8fbfddede13bd04b02788276421f041d6eca9bd86c15e1d221fc",
        "head_0c7eada_validator_output_md_sha256=e57c15b6772e0202fe76fec20d220e435c1010aab7bc410fb45230277fc9ab6a",
        "camp_head_at_head_0c7eada_revalidation=0c7eada85ec92a5a1f5b07e8aa9aea686b220a8d",
        "autodl_DP_HEAD_at_head_0c7eada_revalidation=7a1d33da277a1992ec474b5383a0c963c72e04e4",
    ]:
        assert needle in text


def test_validator_acceptance_records_status_counts_and_readback() -> None:
    text = _audit()

    for needle in [
        "schema_version=dp_native_fallback_risk_training_data_validator_v1",
        "status=dp_native_fallback_risk_training_data_validator_complete",
        "passed=True",
        "enabled=True",
        "validator_enable_flag_used=True",
        "records_checked=15",
        "failed_records=0",
        "errors=0",
        "source_log_readback_required_for_acceptance=True",
        "source_log_readback_enabled=True",
        "read_only_source_log_readback_only=True",
        "current_schema_version=dp_native_fallback_risk_training_data_validator_v1",
        "current_status=dp_native_fallback_risk_training_data_validator_complete",
        "current_passed=True",
        "current_enabled=True",
        "current_records_checked=15",
        "current_failed_records=0",
        "current_errors=0",
        "current_source_log_readback_enabled=True",
        "current_dataset_records_total=60",
        "current_dataset_records_without_feasible_candidate=15",
        "current_dataset_records_with_feasible_candidate=45",
        "current_dataset_records_built=15",
        "current_dataset_failed_records=0",
        "current_dataset_candidate_counts=4",
        "current_dataset_oracle_policies=lane/red/quality,red/lane/quality",
        "latest_schema_version=dp_native_fallback_risk_training_data_validator_v1",
        "latest_status=dp_native_fallback_risk_training_data_validator_complete",
        "latest_passed=True",
        "latest_enabled=True",
        "latest_validator_output_written=True",
        "latest_records_checked=15",
        "latest_failed_records=0",
        "latest_errors=0",
        "latest_source_log_readback_enabled=True",
        "latest_source_log_readback_required_for_acceptance=True",
        "latest_default_off=True",
        "latest_read_only=True",
        "latest_replay_executed=False",
        "latest_candidate_generation_executed=False",
        "latest_camp_training_executed=False",
        "latest_diffusion_planner_executed=False",
        "latest_diffusion_planner_modified=False",
        "latest_dataset_schema_version=dp_native_fallback_risk_training_data_v1",
        "latest_dataset_status=dp_native_fallback_risk_training_data_builder_complete",
        "latest_dataset_records_total=60",
        "latest_dataset_records_without_feasible_candidate=15",
        "latest_dataset_records_with_feasible_candidate=45",
        "latest_dataset_records_built=15",
        "latest_dataset_failed_records=0",
        "latest_dataset_record_count=15",
        "latest_dataset_candidate_counts=4",
        "latest_dataset_oracle_policies=lane/red/quality,red/lane/quality",
        "latest_dataset_atom_schema_versions=dp_camp_v10_14d",
        "latest_dataset_atom_name_counts=14",
        "latest_dataset_selected_index_used_as_feature_any=False",
        "latest_dataset_candidate_rank_used_as_feature_any=False",
        "latest_dataset_fallback_label_is_not_a_deployed_atom_all=True",
        "latest_dataset_training_authorized_any=False",
        "current_head_schema_version=dp_native_fallback_risk_training_data_validator_v1",
        "current_head_status=dp_native_fallback_risk_training_data_validator_complete",
        "current_head_passed=True",
        "current_head_enabled=True",
        "current_head_validator_output_written=True",
        "current_head_records_checked=15",
        "current_head_failed_records=0",
        "current_head_errors=0",
        "current_head_source_log_readback_enabled=True",
        "current_head_source_log_readback_required_for_acceptance=True",
        "current_head_default_off=True",
        "current_head_read_only=True",
        "current_head_replay_executed=False",
        "current_head_candidate_generation_executed=False",
        "current_head_camp_training_executed=False",
        "current_head_diffusion_planner_executed=False",
        "current_head_diffusion_planner_modified=False",
        "current_head_dataset_schema_version=dp_native_fallback_risk_training_data_v1",
        "current_head_dataset_status=dp_native_fallback_risk_training_data_builder_complete",
        "current_head_dataset_records_built=15",
        "current_head_dataset_failed_records=0",
        "current_head_dataset_record_count=15",
        "current_head_dataset_candidate_counts=4",
        "current_head_dataset_oracle_policies=lane/red/quality,red/lane/quality",
        "current_head_dataset_atom_schema_versions=dp_camp_v10_14d",
        "current_head_dataset_atom_name_counts=14",
        "current_head_dataset_selected_index_used_as_feature_any=False",
        "current_head_dataset_candidate_rank_used_as_feature_any=False",
        "current_head_dataset_fallback_label_is_not_a_deployed_atom_all=True",
        "current_head_dataset_training_authorized_any=False",
        "head_0c7eada_schema_version=dp_native_fallback_risk_training_data_validator_v1",
        "head_0c7eada_status=dp_native_fallback_risk_training_data_validator_complete",
        "head_0c7eada_passed=True",
        "head_0c7eada_enabled=True",
        "head_0c7eada_validator_output_written=True",
        "head_0c7eada_records_checked=15",
        "head_0c7eada_failed_records=0",
        "head_0c7eada_errors=0",
        "head_0c7eada_source_log_readback_enabled=True",
        "head_0c7eada_source_log_readback_required_for_acceptance=True",
        "head_0c7eada_default_off=True",
        "head_0c7eada_read_only=True",
        "head_0c7eada_replay_executed=False",
        "head_0c7eada_candidate_generation_executed=False",
        "head_0c7eada_camp_training_executed=False",
        "head_0c7eada_diffusion_planner_executed=False",
        "head_0c7eada_diffusion_planner_modified=False",
        "head_0c7eada_dataset_schema_version=dp_native_fallback_risk_training_data_v1",
        "head_0c7eada_dataset_status=dp_native_fallback_risk_training_data_builder_complete",
        "head_0c7eada_dataset_records_total=60",
        "head_0c7eada_dataset_records_without_feasible_candidate=15",
        "head_0c7eada_dataset_records_with_feasible_candidate=45",
        "head_0c7eada_dataset_records_built=15",
        "head_0c7eada_dataset_failed_records=0",
        "head_0c7eada_dataset_record_count=15",
        "head_0c7eada_dataset_candidate_counts=4",
        "head_0c7eada_dataset_oracle_policies=lane/red/quality,red/lane/quality",
        "head_0c7eada_dataset_atom_schema_versions=dp_camp_v10_14d",
        "head_0c7eada_dataset_atom_name_counts=14",
        "head_0c7eada_dataset_selected_index_used_as_feature_any=False",
        "head_0c7eada_dataset_candidate_rank_used_as_feature_any=False",
        "head_0c7eada_dataset_training_authorized_any=False",
    ]:
        assert needle in text


def test_validator_acceptance_records_validated_dataset_contract() -> None:
    text = _audit()

    for needle in [
        "dataset_schema_validated_by_validator=True",
        "builder_complete_status_validated_by_validator=True",
        "record_counts_validated_by_validator=True",
        "source_log_hashes_validated_by_validator=True",
        "source_feasible_mask_all_false_validated_by_validator=True",
        "source_candidate_generation_contract_validated_by_validator=True",
        "source_candidate_tensor_provenance_validated_by_validator=True",
        "atom_schema_and_nonnegative_atoms_validated_by_validator=True",
        "normalized_atoms_validated_by_validator=True",
        "fallback_dataset_training_sufficiency_claim=False",
    ]:
        assert needle in text


def test_validator_acceptance_forbids_training_replay_dp_and_claims() -> None:
    text = _audit()

    for needle in [
        "replay_execution_authorized=False",
        "candidate_generation_authorized=False",
        "camp_training_authorized=False",
        "camp_retraining_authorized=False",
        "Full36_authorized=False",
        "formal_seeds_11_12_13_authorized=False",
        "dp_modification_authorized=False",
        "reference_blend_authorized=False",
        "guidance_authorized=False",
        "postprocess_postselection_authorized=False",
        "closed_loop_outcome_online_input_authorized=False",
        "selector_promotion_authorized=False",
        "atom_promotion_authorized=False",
        "deployable_checkpoint_claim_authorized=False",
        "safety_benefit_claim_authorized=False",
        "camp_over_dp_top1_claim_authorized=False",
        "fallback_risk_training_authorized_now=False",
        "feasible_ranking_master_change_authorized=False",
        "hard_feasibility_relaxation_authorized=False",
        "all_infeasible_records_added_to_feasible_training=False",
        "production_selector_change_authorized=False",
        "online_selector_change_authorized=False",
        "current_replay_execution_authorized=False",
        "current_candidate_generation_authorized=False",
        "current_camp_training_authorized=False",
        "current_camp_retraining_authorized=False",
        "current_formal_seeds_11_12_13_authorized=False",
        "current_dp_modification_authorized=False",
        "current_selector_promotion_authorized=False",
        "current_atom_promotion_authorized=False",
        "current_safety_benefit_claim_authorized=False",
        "current_camp_over_dp_top1_claim_authorized=False",
        "current_fallback_risk_training_authorized_now=False",
        "current_fallback_dataset_training_sufficiency_claim=False",
        "user_broad_execution_permission_recorded=True",
        "this_validator_acceptance_gate_authorizes_training_replay_dp_or_claims=False",
        "latest_replay_execution_authorized=False",
        "latest_candidate_generation_authorized=False",
        "latest_training_authorized=False",
        "latest_camp_training_authorized=False",
        "latest_camp_retraining_authorized=False",
        "latest_Full36_authorized=False",
        "latest_formal_seeds_11_12_13_authorized=False",
        "latest_dp_modification_authorized=False",
        "latest_reference_blend_authorized=False",
        "latest_guidance_authorized=False",
        "latest_postprocess_postselection_authorized=False",
        "latest_closed_loop_outcome_online_input_authorized=False",
        "latest_production_selector_change_authorized=False",
        "latest_online_selector_change_authorized=False",
        "latest_selector_promotion_authorized=False",
        "latest_atom_promotion_authorized=False",
        "latest_deployable_checkpoint_claim_authorized=False",
        "latest_safety_benefit_claim_authorized=False",
        "latest_camp_over_dp_top1_claim_authorized=False",
        "latest_fallback_dataset_training_sufficiency_claim=False",
        "latest_feasible_ranking_master_change_authorized=False",
        "latest_hard_feasibility_relaxation_authorized=False",
        "latest_all_infeasible_records_added_to_feasible_training=False",
        "current_head_replay_execution_authorized=False",
        "current_head_candidate_generation_authorized=False",
        "current_head_training_authorized=False",
        "current_head_camp_training_authorized=False",
        "current_head_camp_retraining_authorized=False",
        "current_head_dp_modification_authorized=False",
        "current_head_fallback_dataset_training_sufficiency_claim=False",
        "head_0c7eada_replay_execution_authorized=False",
        "head_0c7eada_candidate_generation_authorized=False",
        "head_0c7eada_training_authorized=False",
        "head_0c7eada_camp_training_authorized=False",
        "head_0c7eada_camp_retraining_authorized=False",
        "head_0c7eada_Full36_authorized=False",
        "head_0c7eada_formal_seeds_11_12_13_authorized=False",
        "head_0c7eada_dp_modification_authorized=False",
        "head_0c7eada_reference_blend_authorized=False",
        "head_0c7eada_guidance_authorized=False",
        "head_0c7eada_postprocess_postselection_authorized=False",
        "head_0c7eada_closed_loop_outcome_online_input_authorized=False",
        "head_0c7eada_production_selector_change_authorized=False",
        "head_0c7eada_online_selector_change_authorized=False",
        "head_0c7eada_selector_promotion_authorized=False",
        "head_0c7eada_atom_promotion_authorized=False",
        "head_0c7eada_deployable_checkpoint_claim_authorized=False",
        "head_0c7eada_safety_benefit_claim_authorized=False",
        "head_0c7eada_camp_over_dp_top1_claim_authorized=False",
        "head_0c7eada_fallback_dataset_training_sufficiency_claim=False",
        "head_0c7eada_feasible_ranking_master_change_authorized=False",
        "head_0c7eada_hard_feasibility_relaxation_authorized=False",
        "head_0c7eada_all_infeasible_records_added_to_feasible_training=False",
    ]:
        assert needle in text

    for forbidden in [
        "camp_training_authorized=True",
        "camp_retraining_authorized=True",
        "candidate_generation_authorized=True",
        "dp_modification_authorized=True",
        "selector_promotion_authorized=True",
        "atom_promotion_authorized=True",
        "safety_benefit_claim_authorized=True",
        "camp_over_dp_top1_claim_authorized=True",
        "fallback_risk_training_authorized_now=True",
    ]:
        assert forbidden not in text


def test_validator_acceptance_next_gate_is_training_sufficiency_plan_only() -> None:
    text = _audit()
    iteration_tail = ITERATION_AUDIT.read_text(encoding="utf-8")[-12000:]
    combined = text + iteration_tail

    for needle in [
        "status=fallback_risk_training_data_validator_extension_fixed_artifact_acceptance_passed",
        "status=fallback_risk_training_data_validator_extension_fixed_artifact_acceptance_revalidated",
        "status=fallback_risk_training_data_validator_extension_fixed_artifact_acceptance_current_head_b572505_revalidated",
        "status=fallback_risk_training_data_validator_extension_fixed_artifact_acceptance_current_head_0c7eada_revalidated",
        "fixed_artifact_acceptance_audit_complete=True",
        "validated_fallback_records=15",
        "validated_fallback_dataset_sha256=9dae6215f7b35cd142c37da80c92b38cac1263ee229a5ecb9c4e7c7cd4785018",
        "validated_fallback_dataset_sha256=79e8ddd27b06f6d377819c64dace333e0e36af088505fe784bfee24f89f956c0",
        "validator_output_json_sha256=4baaf581141c8fbfddede13bd04b02788276421f041d6eca9bd86c15e1d221fc",
        "dp_native_training_sufficiency_development_base_plus_addon_static_dp_reward_fixed_artifact_fallback_risk_training_data_training_sufficiency_plan_only",
        "may only plan the training-sufficiency boundary",
        "must predeclare any split",
        "scale-fitting",
        "formal-seed exclusion",
        "must not train CAMP",
        "run replay",
        "generate",
        "modify Diffusion Planner",
        "promote a selector or atom",
    ]:
        assert needle in combined
